package org.rapidpm.jumpstart.vaadin.design.login;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginScreen extends HorizontalLayout {
  protected Label label_username;
  protected Label label_password;
  protected Label tf_language;
  protected Button b_login;
  protected TextField tf_username;
  protected PasswordField pf_password;
  protected ComboBox<String> cb_language;


  public LoginScreen() {
    Design.read(this);
  }
}
